import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MG_Code Blog",
  description: "Generated by create next app",
  icons: [
    {
      url: "/WhatsApp Image 2024-03-20 at 23.49.03_382de109.jpg",
      type: "image/png",
      sizes: "22x22",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background ">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />

          <main className="max-w-3xl mx-auto px-4 py-5 font-mono ">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
